export const NEW_MESSAGES = "NEW_MESSAGES";
export const LISTEN_CONVERSATION = "LISTEN_CONVERSATION";
export const STOP_LISTENING_CONVERSATION = "STOP_LISTENING_CONVERSATION";
export const ERROR = "ERROR";
