export const EVENT_ERROR = "EVENT_ERROR";

// Chat service
export const EVENT_SERVER_INIT_MESSAGE_LIST = "EVENT_SERVER_INIT_MESSAGE_LIST";
export const EVENT_SERVER_SEND_MESSAGE = "EVENT_SERVER_SEND_MESSAGE";
export const EVENT_SERVER_SEND_USER_DATA = "EVENT_SERVER_SEND_USER_DATA";
export const EVENT_SERVER_SEND_MESSAGE_STATUS = "EVENT_SERVER_SEND_MESSAGE_STATUS";
export const EVENT_SERVER_SEND_CHAT_STATE = "EVENT_SERVER_SEND_CHAT_STATE";
export const EVENT_CLIENT_SEND_MESSAGE = "EVENT_CLIENT_SEND_MESSAGE";
export const EVENT_INIT_ROOM = "EVENT_INIT_ROOM";

// Live service
export const NEW_MESSAGES = "NEW_MESSAGES";
export const LISTEN_CONVERSATION = "LISTEN_CONVERSATION";
export const STOP_LISTENING_CONVERSATION = "STOP_LISTENING_CONVERSATION";
